import { theme } from "@/constants/colors";
import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  sheetBackground: {
    backgroundColor: theme.colors.card,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  handleIndicator: {
    width: 48,
    height: 5,
    backgroundColor: theme.colors.textSecondary,
    opacity: 0.3,
  },
  scrollContent: {
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 40,
  },
  header: {
    alignItems: "center",
    marginBottom: 32,
    position: "relative",
    width: "100%",
  },
  closeButton: {
    position: "absolute",
    left: 0,
    top: -4,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.colors.background,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  title: {
    color: theme.colors.textPrimary,
    fontSize: 22,
    fontWeight: "800",
  },
  subtitle: {
    color: theme.colors.textSecondary,
    fontSize: 13,
    marginTop: 6,
  },
  labelRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  label: {
    color: theme.colors.textPrimary,
    fontSize: 13,
    fontWeight: "700",
  },
  optionText: {
    color: theme.colors.textSecondary,
    fontSize: 13,
    marginLeft: 4,
  },
  characterCount: {
    color: theme.colors.textSecondary,
    fontSize: 12,
    fontWeight: "500",
  },
  leftLabelGroup: {
    flexDirection: "row",
    alignItems: "center",
  },
  iconSelectionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 24,
  },
  groupIcon: {
    borderRadius: 16,
    width: 52,
    height: 52,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.background,
    alignItems: "center",
    justifyContent: "center",
  },
  groupIconSelected: {
    borderColor: theme.colors.tabActive,
    backgroundColor: `${theme.colors.tabActive}20`,
  },
  input: {
    height: 56,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.background,
    color: theme.colors.textPrimary,
    paddingHorizontal: 16,
    fontSize: 16,
    marginBottom: 24,
  },
  textArea: {
    height: 100,
    paddingTop: 14,
    textAlignVertical: "top",
  },
  memberSectionContainer: {
    marginTop: 8,
    marginBottom: 32,
    gap: 12,
  },
  memberRowLayout: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    width: "100%",
  },
  memberAddButton: {
    borderRadius: 30,
    width: 56,
    height: 56,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.background,
    alignItems: "center",
    justifyContent: "center",
  },
  memberAddButtonActive: {
    borderColor: theme.colors.tabActive,
    backgroundColor: `${theme.colors.tabActive}20`,
  },
  animatedListContainer: {
    flex: 1,
  },
  friendsListWrapper: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 12,
    borderRadius: 20,
    backgroundColor: theme.colors.background,
  },
  friendItemContainer: {
    alignItems: "center",
    gap: 4,
  },
  friendListButton: {
    borderRadius: 30,
    width: 56,
    height: 56,
    borderWidth: 2,
    borderColor: theme.colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  friendAvatarSize: {
    width: 44,
    height: 44,
    borderRadius: 22,
  },
  friendAvatarSelected: {
    borderWidth: 2,
    borderColor: theme.colors.tabActive,
    backgroundColor: `${theme.colors.tabActive}20`,
  },
  friendName: {
    fontSize: 10,
    color: theme.colors.textPrimary,
  },
  searchBarContainer: {
    flexDirection: "row",
    alignItems: "center",
    height: 52,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.background,
    paddingHorizontal: 14,
    marginTop: 8,
    width: "100%",
  },
  searchIcon: {
    marginRight: 10,
  },
  searchInput: {
    flex: 1,
    height: "100%",
    color: theme.colors.textPrimary,
    fontSize: 15,
  },
  clearButton: {
    padding: 4,
  },
  ctaWrapper: {
    marginTop: 8,
  },
  createButton: {
    height: 56,
    borderRadius: 16,
    backgroundColor: theme.colors.tabActive,
    alignItems: "center",
    justifyContent: "center",
  },
  createButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "700",
  },
});
