services:
  db:
    image: postgres:15-alpine
    container_name: splitsmart_db
    restart: always
    # This environment section tells Docker which variables to look for
    # run this container using the following command inside of the apps folder: docker-compose --env-file api/.env up -v
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - splitsmart_pg_data:/var/lib/postgresql/data

volumes:
  splitsmart_pg_data: